# Generated by Django 3.2.5 on 2021-07-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('txt', models.TextField(max_length=500)),
                ('title', models.TextField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='PostM',
        ),
    ]
