# Generated by Django 3.2.5 on 2021-07-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0002_auto_20210712_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='txt',
            field=models.TextField(max_length=1000),
        ),
    ]
