# Generated by Django 3.2.5 on 2021-07-12 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0004_alter_postmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 17, 41, 29, 214204, tzinfo=utc)),
        ),
    ]
