# Generated by Django 3.2.5 on 2021-07-12 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0007_auto_20210712_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 19, 38, 36, 517750, tzinfo=utc)),
        ),
    ]
